// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// HandleEvent implements HandleEvent operation.
//
// Endpoint where Github pushes the events to.
//
// POST /github/payload
func (UnimplementedHandler) HandleEvent(ctx context.Context, req *ReleasePublishedEvent) error {
	return ht.ErrNotImplemented
}
