openapi: 3.0.0
info:
  title: CageManager API
  description: A very cool api to manage very cool cages :-)
  version: latest
servers:
  - url: https://<cage-manager-api>
paths:
  /cages:
    $ref: "./paths/cages.yaml"

  /{cageId}/deploy: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/deploy.backup.yaml"
  /cages/{cageId}/deploy:
    $ref: "./paths/cages/{cageId}/deploy.yaml"

  /{cageId}/delete: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/delete.yaml"
  /cages/{cageId}:
    $ref: "./paths/cages/{cageId}.yaml"

  /{cageId}/event: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/event.backup.yaml"
  /cages/{cageId}/event:
    $ref: "./paths/cages/{cageId}/event.yaml"

  /{cageId}/public-key: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/public-key.backup.yaml"
  /cages/{cageId}/public-key:
    $ref: "./paths/cages/{cageId}/public-key.yaml"

  /{cageId}/logs/pod_status: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/logs/pod-status.backup.yaml"
  /cages/{cageId}/logs/pod_status:
    $ref: "./paths/cages/{cageId}/logs/pod-status.yaml"

  /{cageId}/logs/algo: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/logs/algo.backup.yaml"
  /cages/{cageId}/logs/algo:
    $ref: "./paths/cages/{cageId}/logs/algo.yaml"

  /{cageId}/logs/{tempPlaceholder}: # TODO -> stop using dv-platform and remove
    $ref: "./paths/cages/{cageId}/logs/{tempPlaceholder}.backup.yaml"
  /cages/{cageId}/logs/{tempPlaceholder}:
    $ref: "./paths/cages/{cageId}/logs/{tempPlaceholder}.yaml"

components:
  schemas:
    Cage:
      $ref: "./schemas/Cage.yaml"
    PodStatus:
      $ref: "./schemas/PodStatus.yaml"
    CageSettings:
      $ref: "./schemas/CageSettings.yaml"

tags:
  - name: crud
    description: CRUD operations on cage resources
  - name: operate
    description: Endpoints to operate a cage
  - name: monitor
    description: Endpoints to monitor a cage
