openapi: 3.0.0
info:
  title: CageManager API
  description: A very cool api to manage very cool cages :-)
  version: latest
servers:
  - url: https://<cage-manager-api>
paths:
  /cages:
    get:
      summary: Get deployed cages.
      tags:
        - crud
      responses:
        "200":
          description: A JSON array of cages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cage"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"

  "/{cageId}/deploy":
    post:
      summary: Deploy a cage
      tags:
        - operate
      description: >
        Deploys a cage defined in a collaboration space.
      parameters:
        - in: path
          name: cageId
          schema:
            type: string
          required: true
          description: Id of the collaboration space
        - in: query
          name: keep_data
          schema:
            type: boolean
            default: true
          required: false
          description: Keep the data associated with this cage.
      requestBody:
        description: Settings for the cage to be deployed
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CageSettings"
      responses:
        "200":
          description: Succesfully deployed cage
        "422":
          description: Could not process the cage deployment request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/422Error"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"

  "/{cageId}/delete":
    post:
      summary: Delete a cage
      tags:
        - crud
      description: >
        Deletes the (deployed) cage linked to a collaboration space.  Sadly this does not use the delete verb. This is to keep backwards portability
      parameters:
        - in: path
          name: cageId
          schema:
            type: string
          required: true
          description: Id of the collaboration space
      responses:
        "200":
          description: Succesfully deployed cage
        "404":
          description: Could not find the cage to be deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404Error"
        "422":
          description: Could not process the request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/422Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"

  "/{cageId}/public-key":
    get:
      summary: Get the public key of a cage.
      tags:
        - operate
      description: "Fetches the public key of a cage."
      parameters:
        - in: path
          name: cageId
          schema:
            type: string
          required: true
          description: Id of the collaboration space
      responses:
        "200":
          description: The RSA public key of this cage.
          content:
            text/plain:
              schema:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"

  "/{cageId}/logs/{tempPlaceholder}":
    get:
      summary: Get the logs of the algo
      tags:
        - monitor
      description: >
        Fetches the logs of the algo running in the cage.
        Right now a placeHolder path variable is added because this will split into multiple endpoints.

      parameters:
        - in: path
          name: cageId
          schema:
            type: string
          required: true
          description: Id of the collaboration space
        - in: path
          name: tempPlaceholder
          schema:
            type: string
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    500Error:
      description: Represents error object
      type: object
      properties:
        message:
          type: string
      required:
        - message
    404Error:
      description: Represents error object
      type: object
      properties:
        message:
          type: string
      required:
        - message
    422Error:
      description: Represents error object
      type: object
      properties:
        message:
          type: string
      required:
        - message
    Cage:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
    CageSettings:
      type: object
      properties:
        app_id:
          type: string
        client_id:
          type: string
        dv_token:
          type: string

        cagepool:
          type: string

        environments:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string

        algo:
          type: object
          properties:
            cron:
              type: array
              items:
                type: object
                required:
                  - expression
                  - type
                properties:
                  expression:
                    type: string
                  type:
                    type: string
            source:
              type: object
              properties:
                registry:
                  type: string
                image:
                  type: string
                tag:
                  type: string
                secret:
                  type: string

tags:
  - name: crud
    description: CRUD operations on cage resources
  - name: operate
    description: Endpoints to operate a cage
  - name: monitor
    description: Endpoints to monitor a cage
