openapi: 3.0.0
info:
  title: ControlPlane API
  version: latest
tags:
  - name: auth
    description: Endpoints related to authorization and authentication
    x-displayName: Auth
  - name: spaces
    description: Endpoints related to collaboration spaces
    x-displayName: Collaboration Spaces

paths:
  /auth/currentCredentials:
    $ref: "./paths/auth/currentCredentialsGET.yaml"
  /collaborationSpaces:
    $ref: "./paths/collaborationSpaces.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
