name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clean recent versions
        run: yarn docusaurus clean-api-docs all

      - name: Generate recent versions
        run: yarn docusaurus gen-api-docs all

      - name: Clean Control Plane legacy versions
        run: yarn docusaurus clean-api-docs:version control-plane:all

      - name: Generate Control Plane legacy versions
        run: yarn docusaurus gen-api-docs:version control-plane:all

      - name: Test build website
        run: yarn build
